language: node_js
sudo: required
services:
  - docker
node_js:
  - 6
python:
  - 3.5
install:
  - pip install -r requirements.txt
  - npm install
  - docker-compose up -d
script:
  - make test
  - make build
