language: node_js
sudo: required
node_js:
  - 6
python:
  - 3.5
install:
  - make install
script:
  - make start &
  - make test
notifications:
  slack: idb3:eVLIH4fI9vghEmPZUxjYdsfl
env:
  - FLASK_PORT=8080
