FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Reddiful

Reddiful is a simple API allowing consumers to view reddit metadata

## Subreddit Collection [/subreddits/{subreddit}]
+ Parameters
    + subreddit (string) - name of the subreddit

+ Attributes
    + accounts_active (number) - number of visitors on the subreddit
    + created (number) - time of creation of the subreddit
    + display_name: news (string) - subreddit name
    + id (string) - unique ID of the subreddit
    + subscribers (number) - number of subscribers to subreddit
    + title (string) - title of the subreddit

### List All Subreddits [GET]

+ Response 200 (application/json)

        [
            {
                "accounts_active": 921,
                "created": 1484806197,
                "display_name": "FireEmblemHeroes",
                "id": "3imv0",
                "subscribers": 52790,
                "title": "Fire Emblem Heroes - Nintendo's Latest Mobile Game"
            },
            {
                "accounts_active": 603,
                "created": 1327266711,
                "display_name": "ProgrammerHumor",
                "id": "2tex6",
                "subscribers": 199848,
                "title": "Programmer Humor"
            },
            {
                "accounts_active": 1338,
                "created": 1201275191,
                "display_name": "food",
                "id": "2qh55",
                "subscribers": 10979227,
                "title": "food"
            }
        ]

## Users Collection [/users/{user}]
+ Parameters
    + user (string) - name of the account

+ Attributes
    + comment_karma (number) - total comment karma generated by this user
    + created (number) - time the account was registered
    + email (string) - email if the user allows it to be seen
    + id (string) - unique ID of the user
    + link_karma (number) - total post karma generated by this user
    + name: john_doe (string) - account name

### List All Users [GET]

+ Response 200 (application/json)

        [
            {
                "comment_karma": 190,
                "created": 1405828618,
                "email": "None",
                "id": "hh8mr",
                "link_karma": 335,
                "name": "batman_jr"
            },
            {
                "comment_karma": 25418,
                "created": 1331171212,
                "email": "poizan@poizan.dk",
                "id": "74344",
                "link_karma": 768,
                "name": "poizan42"
            },
            {
                "comment_karma": 56846,
                "created": 1287044616,
                "email": "ooer@live.com",
                "id": "4fer6",
                "link_karma": 18834,
                "name": "Ooer"
            }
        ]

## Posts Collection [/posts/{post}]
+ Parameters
    + post (string) - title of the post

+ Attributes
    + author_id (string) - author of the post (foreign key to name in Users)
    + created (number) - time of creation
    + gilded (number) - number of times this post is gilded
    + id (string) - unique ID of this post
    + self_post (boolean) - is this a text post
    + nsfw (boolean) - is this post nsfw
    + score (number) - karma count of this post
    + self_text (string) - text of the post is it's a self post
    + subreddit_id (string) - unique ID of the overall subreddit (foreign key to ID of Subreddit)
    + title: me_irl (string) - title of the post
    + url (string) - URL linking to where you go when you click the title

### List All Posts [GET]

+ Response 200 (application/json)

        [
            {
                "author_id": "hh8mr",
                "created": 1486872624,
                "gilded": 0,
                "id": "5th7sz",
                "self_post": True,
                "nsfw": False,
                "score": 1,
                "self_text": "Test Text",
                "subreddit_id": "t5_3imxi",
                "title": "Test",
                "url": "https://www.reddit.com/r/FireEmblemHeroesTest/comments/5th7sz/test/"
            },
            {
                "author_id": "74344",
                "created": 1490143051,
                "gilded": 0,
                "id": "60on5c",
                "self_post": False,
                "nsfw": False,
                "score": 756,
                "self_text": "",
                "subreddit_id": "t5_2tex6",
                "title": "existentialSort",
                "url": "https://i.redd.it/gdoviw37hsmy.jpg"
            },
            {
                "author_id": "4fer6",
                "created": 1490203502,
                "gilded": 0,
                "id": "60tlfl",
                "self_post": True,
                "nsfw": False,
                "score": 13,
                "self_text": "Hey everyone!\n\nThis Friday there will be 8 people at my place including me, all of us have played board games before, and i am excited to introduce **Captain Sonar**. This will be my first play as well, but i think i know the rules. The thing is, 8 people is a lot to manage. Im worried that i might mess up some rules. I want the game to run as smoothly as possible since its not often that i get 8 players. Are there any commonly missed rules or any advice that you guys can give me?\n\nAlso did you all enjoy the game? What did you think about it? How was your experience?",
                "subreddit_id": "t5_2qmjp",
                "title": "Planning on getting Captain Sonar to the table with the full 8-players. Would love some advice",
                "url": "https://www.reddit.com/r/boardgames/comments/60tlfl/planning_on_getting_captain_sonar_to_the_table/"
            }
        ]
        
## Comment Collection [/comments/{comment}]
+ Parameters
    + comment (string) - body of the comment

+ Attributes
    + author_id (string) - author of the comment (foreign key to ID of User)
    + body: this is a comment (string) - body of the comment
    + created (string) - time of the comment's post
    + gilded (number) - number of times this comment is gilded
    + id (string) - unique ID of this comment
    + link_id (string) - unique ID of the overall post (foreign key to ID of Post)
    + score (number) - karma of the comment
    + subreddit_id (string) - unique ID of the overall subreddit (foreign key to ID of Subreddit)
    
    
    

### List All Comments [GET]

+ Response 200 (application/json)

        [
            {
                "author_id": "hh8mr",
                "body": "comment 2",
                "created": 1488274311,
                "gilded": 0,
                "id": "deaw2vi",
                "link_id": "t3_5th7sz",
                "score": 1,
                "subreddit_id": "3imxi"
            },
            {
                "author_id": "74344",
                "body": "> Despite claiming ownership, Canada provides no medical or social services to any of the inhabitants of Hans Island.\n\nYou could also say that they do provide medical and social services to all the inhabitants though.",
                "created": 1490098110,
                "gilded": 0,
                "id": "df7d781",
                "link_id": "t3_60h6ga",
                "score": 2,
                "subreddit_id": "2qqjc"
            },
            {
                "author_id": "4fer6",
                "body": "Spilled a glass of diet Pepsi all over Cash 'n' Guns (first time playing). It was of course an accident and they immediately offered to help clean them, and failing that buy me the game again.\n\nThankfully, because it was diet (no sugar) the cards were able to be saved and now you couldn't tell it ever happened.",
                "created": 1490146785,
                "gilded": 0,
                "id": "df8425r",
                "link_id": "t3_60nyom",
                "score": 3,
                "subreddit_id": "2qmjp"
            }
        ]